import {SoundEffect} from '../lib/sfxr.mjs';

// Game sound effects (generated by 'sfxr.js')
export const soundTypes = {
	SELECT: 'select',
	REVIVE: 'reset',
	SHOOT: 'shoot',
	POWER: 'power',
	LEVEL_UP: 'level-up',
	PLAYER_HIT: 'player-hit',
	BULLET_HIT: 'bullet-hit',
	ASTEROID_DESTORY: 'asteroid-destroy',
};

export const soundCodes = {
	[soundTypes.SELECT]: '111114YA69VjV2TF883n6f74g6pdmvw94esjz2Fg9dVLMafmEXKsLhDNrqyMiHgYJLUFEU4BBbMM2fbPNNkEPnFr2gKqHzZest5dM9rcxKvMBfZaNVG7wsFV',
	[soundTypes.REVIVE]: '34T6PkuM9azcqQRP2uhqSKehYPVttMZPtXpjTTUjUwxb7py2H6TKgBffhrzZ7nPmKhP9JD3gEhifVkUezyWGSUnQyk8ogjYL61H2E9d5KhKMhhHhaxT3G4jR1',
	[soundTypes.SHOOT]: '111112tu2RTz4ZLfm6nwnmzVVYDerCJ1GUa66TYpw6EgKckrbkxXbT14CJiEqBnf3cjD3aFriqdKZs6A8QJB2AYqbmYX8qYaJRnwaipyeGThYFXGoKQKWwgB',
	[soundTypes.LEVEL_UP]: '111119SowJUqZyfe4jLRUfMiWf8c8WYnkjRBJUL3ZZaCqfAeNPhf9rVc62kRS3jD3J63z77A6QF6Mhazdo7kb9hjbyQ3JUTCLeAmStvwTzmPMhnSREk4jzYP',
	[soundTypes.POWER]: '34T6PksDM6sxLWXsKMV54x6nBYTVK2X82XguTcaNo2PNHaSYwAgcpjW5ZD5MLL4xexbsTeVEWu6cDStLHKr2ey2kqMcTGr9p7MYBp157yy7xG3Mhu9rpQWJqd',
	[soundTypes.PLAYER_HIT]: '7BMHBGQKT6faneej8J2UfgXkv259Mh1u9B4bysSRxEYy7VtvWt4cdFK5MwuM5pAWp8rdGDfJai6329LzskzZkh9ipbXn4rDdD1YQjJYCzXxoV1JgQzadPpXfu',
	[soundTypes.BULLET_HIT]: '7BMHBGLmaZAt72j4pAcPAVnSrSTf2sb9NC6LKmg8cmfTtK5cFcHvPcUGnfH99T7EAeTwdLUYEMKEHKYm4VTVLuJywmfAAR3XthQc3v361s6Lq6UJQLBuW6a6b',
	[soundTypes.ASTEROID_DESTORY]: '7BMHBGGGKzwmnk2LXPSFk2ZR1UCBQV7GsbQ51LNWWc2ZJkkZBaLs1QbPoCe86BcCp69QnKH67dcF48hGfrriBi5Xdf4a8jnYma3QvDjHm5QQcR5cezjbEECBR',
};

let generateSound = (code) => new SoundEffect(code).generate();

export const soundEffects = Object.keys(soundCodes).reduce((effects, key) => {
	effects[key] = generateSound(soundCodes[key]).getAudio();
	return effects;
}, {});
